### ISSUE TITLE
Game won't open 

### ISSUE THREAD

**Issue by AstralTM** [OpenSauce04/EpiphanyIssues#63]
**Describe the bug**
---

So after 1 run my game crashed while i was trying to play another run and now i can't open it. after deleting epiphany from mod folder, the game opened again without problems

**To Reproduce**
---
-start a run
-get crash

**EpiphanyDiag info**
---

**Screenshots**
---

**Version information:** 
i can't open the console because my game can't run while epiphany is in my mod folder
---
 - Installed wave number: 
 - Version number: 

**Additional context**
---

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/11511827/EpiphanyDiagnostics.tar.gz)

**Comment by mohsin4547** [comment]
this is a problem with all of tboi big mods in the latest update
just put --luaheapsize 0 in the game's launch commands

**Comment by OpenSauce04** [comment]
You are using a pirated version of Isaac on the v1.7.9c version. This version is known to be incredibly unstable, and was rolled back hours after it was released. Please downgrade to v1.7.9b and let me know if the issue still happens
Also, you'll have to delete your `data/epiphany` folder, as it has become full of garbage data, supposedly due to an error
